spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://app_db:3306/b5joz44TkRE4rXhUhCo3_db
    username: UJ2Hk8KEBa7RgQ2QP7jo_user
    password: hh558RTwH4UuTkRuMUR8aUgkq7ZsP8

  redis:
    host: app_cache
    port: 6379

  jwt:
    secret: VY8bBm7p93fC2SZJ6bZBeJHQZKvHfHTVJhdXjC9TGg8KLYooLXL4SvHcGfAf

  chain:
    api-token: d17TEKsti3aNZKH88NxjrcQqtl4z9E1TZxEtNMLn

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: sjsb4838@gmail.com
    password: aofx axhb hbgk qyzc
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true

  oauth:
    password: oKd7SVhTuW2HCfdppcLczrqz6enn7cbeadfrxGRGYcfCd8RaN9
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      rest-api-key: 127265cef17dc44834bc915935e7f20d
      redirect-uri: https://h.princip.es/kakaoLogin
      user-info-uri: https://kapi.kakao.com/v2/user/me
      client-secret: lmZwTCJ5DVrvee6I087Gxq4zfJi8XNaq
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      rest-api-key: Zn5JnI_lZiRttfFL7uTR
      redirect-uri: https://h.princip.es/naverLogin
      user-info-uri: https://openapi.naver.com/v1/nid/me

server:
  servlet:
    encoding:
      charset: utf-8

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE # Hibernate 5.2 이상 버전에서 사용 가능합니다.